### ISSUE TITLE
About list of extended flags

### ISSUE THREAD

**Issue by jiayily** [nubot-nudt/ElC-OIS#4]
Then list of extended flags is global. But a point may need to be extended by one query point but not by another one. Obviously list of extended flags can accelerate the runtime. But does this have any bad impact on the result?

**Comment by dwbzxc** [comment]
Hi! Thanks for your interest. Since the points in the spherical neighbors regarding the shortest ellipsoidal axis as the diameter, most of their neighbor points might be covered by query points in the ellipsoidal neighbor. Thus, the results of using the extended flags or not should be close, although we haven't made this ablation study yet. Feel free to have a test!
